In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("purchase.csv")
df.head()
## df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  object
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  object
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), object(13)
memory usage: 1.1+ MB

Use isnull to check even bigger db

In [31]:
df['Credit Card'] = df['Credit Card'].astype(str)
df['CC Security Code'] = df['CC Security Code'].astype(str)

1. total purchase avg

2. how many used english

3. job of users

4. what jobs used most $

5. what job purchsed most frequently

6. bondellen@williams-garza.com used how much?

7. MasterCard and purchased something more than 50$

8. how many used Windows

9. % of users what used Windows, Linux, Mac

1.

In [7]:
df.describe()
df['Purchase Price'].mean()

50.34730200000025

In [33]:
df['Purchase Price'].max()

99.99

In [35]:
df['Purchase Price'].describe()

count    10000.000000
mean        50.347302
std         29.015836
min          0.000000
25%         25.150000
50%         50.505000
75%         75.770000
max         99.990000
Name: Purchase Price, dtype: float64

2.

In [36]:
df.groupby('Language')['Purchase Price'].count()

Language
de    1155
el    1137
en    1098
es    1095
fr    1097
it    1086
pt    1118
ru    1155
zh    1059
Name: Purchase Price, dtype: int64

In [37]:
df['Language'].unique()

array(['el', 'fr', 'de', 'es', 'ru', 'pt', 'zh', 'en', 'it'], dtype=object)

3.

In [23]:
len(df['Job'].unique())
df['Job'].nunique()

623

4.

In [30]:
df.groupby('Job')['Purchase Price'].sum().sort_values(ascending=False)

Job
Dietitian                      1605.30
Lawyer                         1603.85
Purchasing manager             1577.97
Therapist, art                 1526.31
Clinical cytogeneticist        1495.92
                                ...
Music therapist                 327.50
Actuary                         262.72
Information systems manager     241.42
Marketing executive             234.08
Art gallery manager             219.05
Name: Purchase Price, Length: 623, dtype: float64

In [40]:
df.groupby('Job')['Purchase Price'].sum().sort_values(ascending=False)[:10]

Job
Dietitian                            1605.30
Lawyer                               1603.85
Purchasing manager                   1577.97
Therapist, art                       1526.31
Clinical cytogeneticist              1495.92
Research officer, political party    1488.79
Designer, jewellery                  1482.20
Interior and spatial designer        1466.20
Network engineer                     1421.73
Social researcher                    1416.34
Name: Purchase Price, dtype: float64

5.

In [41]:
df['Job'].value_counts()

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
                                     ..
Stage manager                         7
Editor, film/video                    6
Actuary                               6
Investment analyst                    5
Information systems manager           5
Name: Job, Length: 623, dtype: int64

6.

In [42]:
df[df['Email']=='bondellen@williams-garza.com']
df[df['Email'].str.lower() =='bondellen@williams-garza.com']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1234,"2470 Maria Manors Suite 185\nJoneshaven, MN 87251",82 UX,PM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.5.20) G...,"Cole, King and Bowers",4926535242672853,09/21,188,American Express,bondellen@williams-garza.com,Planning and development surveyor,159.182.3.50,ru,77.88

7.

In [14]:
df.loc[(df['Purchase Price']>= 50) & (df['CC Provider'] == 'Mastercard')]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

Enligh always beware lol

In [43]:
df.loc[(df['Purchase Price']>= 50) & (df['CC Provider'].str.lower() == 'mastercard')]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

In [44]:
len(df.loc[(df['Purchase Price']>= 50) & (df['CC Provider'].str.lower() == 'mastercard')])

405

8.

In [22]:
df.groupby('Browser Info')['Purchase Price'].count()

Browser Info
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 rv:2.0; sl-SI) AppleWebKit/533.25.6 (KHTML, like Gecko) Version/4.0 Safari/533.25.6      1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 rv:4.0; en-US) AppleWebKit/535.34.7 (KHTML, like Gecko) Version/5.0 Safari/535.34.7      1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 rv:5.0; sl-SI) AppleWebKit/532.10.4 (KHTML, like Gecko) Version/5.0.2 Safari/532.10.4    1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 rv:6.0; en-US) AppleWebKit/533.45.4 (KHTML, like Gecko) Version/4.1 Safari/533.45.4      1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0) AppleWebKit/5321 (KHTML, like Gecko) Chrome/14.0.824.0 Safari/5321                      1
                                                                                                                                      ..
Opera/9.99.(X11; Linux i686; sl-SI) Presto/2.9.186 Version/12.00                                                                       1
Opera/9.99.(X11; Linux x86_64; en-US) Presto/2.9.172 Version/12.00                                                                     1
Opera/9.99.(X11; Linux x86_64; en-US) Presto/2.9.176 Version/10.00                                                                     1
Opera/9.99.(X11; Linux x86_64; it-IT) Presto/2.9.164 Version/10.00                                                                     1
Opera/9.99.(X11; Linux x86_64; it-IT) Presto/2.9.190 Version/11.00                                                                     1
Name: Purchase Price, Length: 8287, dtype: int64

In [54]:
answer8 = df[df["Browser Info"].str.contains('Windows')]

answer8 = df[df["Browser Info"].str.lower().str.contains('windows')]

answer8

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
14,"8774 Jason Keys Suite 427\nEast Scottborough, ...",70 zH,AM,Mozilla/5.0 (Windows 98; it-IT; rv:1.9.2.20) G...,"Leach, Howe and Ferguson",869967499275071,09/22,427,VISA 16 digit,aburns@yahoo.com,Acupuncturist,50.25.148.1,de,24.18
15,"31730 Chelsea Crest\nBlakemouth, CT 90395-0620",41 Cj,PM,Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....,Garcia-Steele,180069437020404,04/25,404,Diners Club / Carte Blanche,amanda39@yahoo.com,Retail manager,53.176.235.33,el,71.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,"0154 Green Forest\nNew Timothy, IL 33670-4620",11 MC,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows 98;...,Williams-Walker,4207292109379681,10/16,571,Diners Club / Carte Blanche,hudsonmichael@pace.com,Charity fundraiser,136.169.160.82,de,89.76
9989,"5674 Cruz Trace\nNew Shelby, KY 51047-5469",12 Kf,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Vargas, Nichols and Martinez",5278049688438382,12/23,996,VISA 16 digit,walterswilliam@hotmail.com,Community development worker,39.162.164.169,pt,17.18
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63

9.

In [55]:
windows = df[df["Browser Info"].str.lower().str.contains('windows')]
linux = df[df["Browser Info"].str.lower().str.contains('linux')]
mac = df[df["Browser Info"].str.lower().str.contains('mac')]

print(len(windows) / len(df))
print(len(linux) / len(df))
print(len(mac) / len(df))

print(len(windows) + len(linux) + len(mac))

0.4994
0.2322
0.2684
10000